apiVersion: v1
kind: Service
metadata:
  name: {{ include "bobravoz-grpc.fullname" . }}-hub
  labels:
    control-plane: controller-manager
  {{- include "bobravoz-grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hub.type }}
  selector:
    app.kubernetes.io/name: bobravoz-grpc
    control-plane: controller-manager
    {{- include "bobravoz-grpc.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.hub.ports | toYaml | nindent 2 }}
