apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bobravoz-grpc.fullname" . }}-manager-role
  labels:
  {{- include "bobravoz-grpc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bubustack.io
  resources:
  - engrams
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bubustack.io
  resources:
  - stories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.bubustack.io
  resources:
  - engramtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runs.bubustack.io
  resources:
  - stepruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runs.bubustack.io
  resources:
  - stepruns/status
  - storyruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runs.bubustack.io
  resources:
  - storyruns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runs.bubustack.io
  resources:
  - storyruns/finalizers
  verbs:
  - update
- apiGroups:
  - transport.bubustack.io
  resources:
  - transportbindings
  - transports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transport.bubustack.io
  resources:
  - transportbindings/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bobravoz-grpc.fullname" . }}-manager-rolebinding
  labels:
  {{- include "bobravoz-grpc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "bobravoz-grpc.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "bobravoz-grpc.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
