apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "bobravoz-grpc.fullname" . }}-serving-cert
  labels:
  {{- include "bobravoz-grpc.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "bobravoz-grpc.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "bobravoz-grpc.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: ClusterIssuer
    name: bobrapet-shared-ca
  privateKey:
    rotationPolicy: Always
  secretName: bobravoz-grpc-webhook-server-cert
