apiVersion: v1
kind: Service
metadata:
  name: {{ include "bobravoz-grpc.fullname" . }}-webhook-service
  labels:
  {{- include "bobravoz-grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app.kubernetes.io/name: bobravoz-grpc
    control-plane: controller-manager
    {{- include "bobravoz-grpc.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
