apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "bobrapet.fullname" . }}-bobrapet-hub-tls
  labels:
  {{- include "bobrapet.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "bobrapet.fullname" . }}-controller-manager.bobrapet-system.svc'
  - '{{ include "bobrapet.fullname" . }}-controller-manager.bobrapet-system.svc.{{ .Values.kubernetesClusterDomain
    }}'
  issuerRef:
    kind: ClusterIssuer
    name: '{{ include "bobrapet.fullname" . }}-shared-ca'
  privateKey:
    rotationPolicy: Always
  secretName: bobrapet-hub-tls
