apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bobrapet.fullname" . }}-runs-storyrun-editor-role
  labels:
  {{- include "bobrapet.labels" . | nindent 4 }}
rules:
- apiGroups:
  - runs.bubustack.io
  resources:
  - storyruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runs.bubustack.io
  resources:
  - storyruns/status
  verbs:
  - get
