apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "bobrapet.fullname" . }}-serving-cert
  labels:
  {{- include "bobrapet.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "bobrapet.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "bobrapet.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: ClusterIssuer
    name: '{{ include "bobrapet.fullname" . }}-shared-ca'
  privateKey:
    rotationPolicy: Always
  secretName: {{ include "bobrapet.fullname" . }}-webhook-server-cert
